# Setup things related to Sway
---
- name: Install packages needed in Sway
  become: true
  package:
    name:
      - sway
      - swaylock
      - swaybg
      - swayidle
      - foot
      - bemenu
      - brightnessctl
      - network-manager-applet
      - blueman # bluetooth applet
      - kanshi # dynamic display configuration
      - dunst
      - waybar
      - fuzzel # launcher
    state: present

- name: Ensure projects directory
  file:
    path: "{{ dotfiles_target }}/{{ item }}"
    state: directory
  loop:
    - sway
    - waybar

- name: Symlink config
  file:
    src: "{{ dotfiles_dir }}/{{ item }}"
    dest: "{{ dotfiles_target }}/{{ item }}"
    state: link
  loop:
    - sway/config
    - waybar/config
